#====================================================================
# File automatically generated by ES3  
# This file regenerated each time you run EISC Studio, so save under a 
# new name if you hand edit, or it will be overwritten.
#				www.adc.co.kr
#====================================================================



ECHO	=	echo.exe
CC	=	ae32000-elf-gcc
AS	=	ae32000-elf-as
LD	=	ae32000-elf-ld
AR	=	ae32000-elf-ar
OBJCOPY	=	ae32000-elf-objcopy
OBJDUMP	=	ae32000-elf-objdump
CFLAGS	=	 -g -fno-strength-reduce -Wall 
ASFLAGS	=	 -gstabs 
LDFLAGS	=	-Wall -nostartfiles -lgcc -lc -lm -Wl,--warn-common 
DISFLAGS	=	-dzShxl
ARFLAGS	=	rcusv
#====== Directory =====
OUTPUTDIR	=	output/
OBJDIR	=	obj/
INCDIR	=	\
	 -I"C:/ADChips/SDK/include"
INCDIR	+=	\
	 -I"C:/ADChips/SDK/include"
LIBDIR	=	
LIBS	=	\
	C:/ADChips/SDK/lib/libadStar.a\
	C:/ADChips/SDK/lib/libjpeg.a

SOURCES	 += P10_3940.c
SOURCES	 += adStarInit.c
SOURCES	 += startup_adstar.s
SOURCES	 += main.c
SOURCES	 += CircularQueue.c
SOURCES	 += Common.c
SOURCES	 += Event.c
SOURCES	 += U2429.c
SOURCES	 += ST_2710_interrupt.c
SOURCES	 += ADF4351.c
SOURCES	 += ST_2710_GUI.c
SOURCES	 += ST_2710.c
SOURCES	 += ymodem.c
SOURCES	 += LCDCtrl.c
SOURCES	 += Key.c
SOURCES	 += Cpu.c
SOURCES	 += Util.c
SOURCES	 += ResourceManager.c
SOURCES	 += ST_2710_GUI_Comm.c
SOURCES	 += ST_2710_GUI_Manager.c
SOURCES	 += ScrollEdit.c
SOURCES	 += ST_2710_GUI_Amp.c
SOURCES	 += ST_2710_GUI_VHF.c
SOURCES	 += ST_2710_GUI_Radio.c
SOURCES	 += ChannelScanner.c
SOURCES	 += FrequencyScanner.c

OBJECTS	 += ${OBJDIR}P10_3940.o
OBJECTS	 += ${OBJDIR}adStarInit.o
OBJECTS	 += ${OBJDIR}startup_adstar.o
OBJECTS	 += ${OBJDIR}main.o
OBJECTS	 += ${OBJDIR}CircularQueue.o
OBJECTS	 += ${OBJDIR}Common.o
OBJECTS	 += ${OBJDIR}Event.o
OBJECTS	 += ${OBJDIR}U2429.o
OBJECTS	 += ${OBJDIR}ST_2710_interrupt.o
OBJECTS	 += ${OBJDIR}ADF4351.o
OBJECTS	 += ${OBJDIR}ST_2710_GUI.o
OBJECTS	 += ${OBJDIR}ST_2710.o
OBJECTS	 += ${OBJDIR}ymodem.o
OBJECTS	 += ${OBJDIR}LCDCtrl.o
OBJECTS	 += ${OBJDIR}Key.o
OBJECTS	 += ${OBJDIR}Cpu.o
OBJECTS	 += ${OBJDIR}Util.o
OBJECTS	 += ${OBJDIR}ResourceManager.o
OBJECTS	 += ${OBJDIR}ST_2710_GUI_Comm.o
OBJECTS	 += ${OBJDIR}ST_2710_GUI_Manager.o
OBJECTS	 += ${OBJDIR}ScrollEdit.o
OBJECTS	 += ${OBJDIR}ST_2710_GUI_Amp.o
OBJECTS	 += ${OBJDIR}ST_2710_GUI_VHF.o
OBJECTS	 += ${OBJDIR}ST_2710_GUI_Radio.o
OBJECTS	 += ${OBJDIR}ChannelScanner.o
OBJECTS	 += ${OBJDIR}FrequencyScanner.o

DEPS	 += ${OBJDIR}P10_3940.d
DEPS	 += ${OBJDIR}adStarInit.d
DEPS	 += ${OBJDIR}startup_adstar.d
DEPS	 += ${OBJDIR}main.d
DEPS	 += ${OBJDIR}CircularQueue.d
DEPS	 += ${OBJDIR}Common.d
DEPS	 += ${OBJDIR}Event.d
DEPS	 += ${OBJDIR}U2429.d
DEPS	 += ${OBJDIR}ST_2710_interrupt.d
DEPS	 += ${OBJDIR}ADF4351.d
DEPS	 += ${OBJDIR}ST_2710_GUI.d
DEPS	 += ${OBJDIR}ST_2710.d
DEPS	 += ${OBJDIR}ymodem.d
DEPS	 += ${OBJDIR}LCDCtrl.d
DEPS	 += ${OBJDIR}Key.d
DEPS	 += ${OBJDIR}Cpu.d
DEPS	 += ${OBJDIR}Util.d
DEPS	 += ${OBJDIR}ResourceManager.d
DEPS	 += ${OBJDIR}ST_2710_GUI_Comm.d
DEPS	 += ${OBJDIR}ST_2710_GUI_Manager.d
DEPS	 += ${OBJDIR}ScrollEdit.d
DEPS	 += ${OBJDIR}ST_2710_GUI_Amp.d
DEPS	 += ${OBJDIR}ST_2710_GUI_VHF.d
DEPS	 += ${OBJDIR}ST_2710_GUI_Radio.d
DEPS	 += ${OBJDIR}ChannelScanner.d
DEPS	 += ${OBJDIR}FrequencyScanner.d



#====== TAGET Define =====
TARGET	=	$(OUTPUTDIR)Target.elf

BINARY	=	$(TARGET).bin

HEX	=	$(TARGET).hex

DISASSEMBLE	=	$(TARGET).dis

ALL	:	$(TARGET) $(BINARY) 

all	:	$(TARGET) $(BINARY) 

binary	:	$(BINARY)

bin	:	$(BINARY)

hex	:	$(HEX)

disassemble	:	$(DISASSEMBLE)

dis	:	$(DISASSEMBLE)

clean	:
	@$(ECHO) 'Deleting intermediate and output files... '
	rm -f $(OBJECTS) $(TARGET) $(DISASSEMBLE) $(BINARY) $(DEPS)
	@$(ECHO) ' '

cleanall	:
	@$(ECHO) 'Deleting intermediate and output files... '
	rm -f $(OBJECTS) $(TARGET) $(DISASSEMBLE) $(BINARY) $(DEPS)
	@$(ECHO) ' '

cleanobj	:
	@$(ECHO) 'Deleting intermediate files... '
	rm -f $(OBJECTS) 
	@$(ECHO) ' '

cleanbin	:
	rm -f $(BINARY)
	@$(ECHO) ' '

cleandis	:
	rm -f $(DISASSEMBLE)
	@$(ECHO) ' '

ifeq ($(FULLMSG),no)
ECHOMARK = @
else
ECHOMARK = 
endif

-include ${OBJDIR}P10_3940.d
-include ${OBJDIR}adStarInit.d
-include ${OBJDIR}startup_adstar.d
-include ${OBJDIR}main.d
-include ${OBJDIR}CircularQueue.d
-include ${OBJDIR}Common.d
-include ${OBJDIR}Event.d
-include ${OBJDIR}U2429.d
-include ${OBJDIR}ST_2710_interrupt.d
-include ${OBJDIR}ADF4351.d
-include ${OBJDIR}ST_2710_GUI.d
-include ${OBJDIR}ST_2710.d
-include ${OBJDIR}ymodem.d
-include ${OBJDIR}LCDCtrl.d
-include ${OBJDIR}Key.d
-include ${OBJDIR}Cpu.d
-include ${OBJDIR}Util.d
-include ${OBJDIR}ResourceManager.d
-include ${OBJDIR}ST_2710_GUI_Comm.d
-include ${OBJDIR}ST_2710_GUI_Manager.d
-include ${OBJDIR}ScrollEdit.d
-include ${OBJDIR}ST_2710_GUI_Amp.d
-include ${OBJDIR}ST_2710_GUI_VHF.d
-include ${OBJDIR}ST_2710_GUI_Radio.d
-include ${OBJDIR}ChannelScanner.d
-include ${OBJDIR}FrequencyScanner.d

#============= TARGET ====================
${TARGET} : Makefile.mk ${OBJECTS} ${LIBS} C:/ADChips/SDK/startup/adstar_ram.ld
	@$(ECHO) 'Linking...'
	$(ECHOMARK)$(CC) -o $(TARGET) $(OBJECTS) $(LIBDIR) -Xlinker --start-group $(LIBS) -Xlinker --end-group $(LDFLAGS) -Xlinker -T"C:/ADChips/SDK/startup/adstar_ram.ld"
	@$(ECHO) 'Finished building : $@ '
	@$(ECHO) ' '

$(BINARY): $(TARGET)
	@$(ECHO) 'Generating binary file...'
	$(ECHOMARK)$(OBJCOPY) -O binary $(TARGET) $@
	@$(ECHO) 'Finished building : $@ '
	@$(ECHO) ' '
	@$(ECHO) 'Program section information '
	$(ECHOMARK)size $(TARGET)
	@$(ECHO) ' '
	@$(ECHO) '======= Event for Atfer Build ======='
	MakeBin.bat
	@$(ECHO) ' '

$(DISASSEMBLE) : $(TARGET)
	@$(ECHO) 'Generating disassemble file...'
	$(ECHOMARK)$(OBJDUMP) $(DISFLAGS) $(TARGET) > $@ 
	@$(ECHO) 'Finished building : $@ '
	@$(ECHO) ' '

${OBJDIR}P10_3940.o : P10_3940.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}adStarInit.o : adStarInit.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}startup_adstar.o : startup_adstar.s
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) -Wa,$(ASFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}main.o : main.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}CircularQueue.o : CircularQueue.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}Common.o : Common.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}Event.o : Event.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}U2429.o : U2429.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ST_2710_interrupt.o : ST_2710_interrupt.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ADF4351.o : ADF4351.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ST_2710_GUI.o : ST_2710_GUI.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ST_2710.o : ST_2710.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ymodem.o : ymodem.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}LCDCtrl.o : LCDCtrl.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}Key.o : Key.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}Cpu.o : Cpu.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}Util.o : Util.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ResourceManager.o : ResourceManager.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ST_2710_GUI_Comm.o : ST_2710_GUI_Comm.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ST_2710_GUI_Manager.o : ST_2710_GUI_Manager.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ScrollEdit.o : ScrollEdit.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ST_2710_GUI_Amp.o : ST_2710_GUI_Amp.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ST_2710_GUI_VHF.o : ST_2710_GUI_VHF.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ST_2710_GUI_Radio.o : ST_2710_GUI_Radio.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ChannelScanner.o : ChannelScanner.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}FrequencyScanner.o : FrequencyScanner.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

